[package]
name = "tlt-decrypt-rs"
version = "0.1.0"
authors = ["Colin Wallace <colin@mooooo.ooo>"]

[dependencies]
ansi_term = "0.11"
euclid = "0.18"
image = "0.19"
imageproc = "0.15"
lazy_static = "1.0"
new-ordered-float = "1.0"
rect-iter = "0.1.9"
